apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-giox
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-awkh-tenant/rhtap-demo-app/hacbs-test-project-giox@sha256:1b1da1200e43327cd0656ee1bcbc0c2cabd2875a7d623bf82512ebd024ddae22
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
